app:
  port: 3000

fabric:
  ca:
    url: "https://localhost:7054"
    caName: "ca-org1"
    tlsCACert: "/home/kwanny/ZJURate-chaincode/fabric-samples/test-network/organizations/fabric-ca/org1/ca-cert.pem"
  client:
    homeDir: "/home/kwanny/ZJURate-chaincode/wallet/org1"
    mspDir: "msp"
  registrar:
    id: "admin"
    secret: "adminpw"
  peers:
    - address: "localhost:7051"
      serverNameOverride: "peer0.org1.example.com"
      tlsCACertPath: "/home/kwanny/ZJURate-chaincode/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem"

jwt:
  secretKey: "supersecretjwtkeyforzjurate"